changing first commit and Editorial commit descriptions
standardebooks/web pull request #155
Opened 2022-01-04 02:54 UTC by pcrooker

here is the pull request for issue #153

2022-01-06 03:16 UTC, acabal requested changes
Great work, thanks. Just a few minor tweaks when you have a minute.

2022-01-06 03:16 UTC, acabal commented on www/contribute/producing-an-ebook-step-by-step.php
> +					<p>Don’t use the [Editorial] flag for typographical changes such as hyphenation or for changing the case of letters or words.</p>
This is not quite right, they should do that, since modernize-spelling adjusts hyphenation

2022-01-06 03:16 UTC, acabal commented on www/contribute/producing-an-ebook-step-by-step.php
> +				<p>Each commit has an accompanying message describing the changes we are making. Please use the commit messages as they are written here in this guide as the editors rely on these words when they
Can you change this to "rely on these messages"

2022-01-08 00:58 UTC, pcrooker commented
Alex, I don't really know what happened, but somehow I've pushed an update that referenced a second pull request as well  - probably because I used this commit message "attempt #2" - it appears the hash has some specific meaning to github despite it being in a quoted string. What to do?

2022-01-08 01:46 UTC, acabal commented
That's fine,I can squash this down anyway. Thanks!

2022-01-08 01:46 UTC, merged